data= (b'\r\nVlan1 is administratively down, line protocol is down \r\n  Hardware is '
 b'EtherSVI, address is 34a8.4e49.4740 (bia 34a8.4e49.4740)\r\n  MTU 1500 byt'
 b'es, BW 1000000 Kbit/sec, DLY 10 usec, \r\n     reliability 255/255, txload'
 b' 1/255, rxload 1/255\r\n  Encapsulation ARPA, loopback not set\r\n  Keepaliv'
 b'e not supported \r\n  ARP type: ARPA, ARP Timeout 04:00:00\r\n  Last input 0'
 b'0:03:25, output never, output hang never\r\n  Last clearing of "show inter'
 b'face" counters never\r\n  Input queue: 0/75/0/0 (size/max/drops/flushes); '
 b'Total output drops: 0\r\n  Queueing strategy: fifo\r\n  Output queue: 0/40 ('
 b'size/max)\r\n  5 minute input rate 0 bits/sec, 0 packets/sec\r\n  5 minute o'
 b'utput rate 0 bits/sec, 0 packets/sec\r\n     244033 packets input, 5299893'
 b'4 bytes, 0 no buffer\r\n     Received 0 broadcasts (0 IP multicasts)\r\n    '
 b' 0 runts, 0 giants, 0 throttles \r\n     0 input errors, 0 CRC, 0 frame, 0'
 b' overrun, 0 ignored\r\n     0 packets output, 0 bytes, 0 underruns\r\n     0'
 b' output errors, 1 interface resets\r\n     0 unknown protocol drops\r\n     '
 b'0 output buffer failures, 0 output buffers swapped out\r\nVlan6 is up, lin'
 b'e protocol is up \r\n  Hardware is EtherSVI, address is 34a8.4e49.4741 (bi'
 b'a 34a8.4e49.4741)\r\n  Internet address is 167.118.106.237/24\r\n  MTU 1500 '
 b'bytes, BW 1000000 Kbit/sec, DLY 10 usec, \r\n     reliability 255/255, txl'
 b'oad 1/255, rxload 1/255\r\n  Encapsulation ARPA, loopback not set\r\n  Keepa'
 b'live not supported \r\n  ARP type: ARPA, ARP Timeout 04:00:00\r\n  Last inpu'
 b't 00:00:00, output 00:00:00, output hang never\r\n  Last clearing of "show'
 b' interface" counters never\r\n  Input queue: 0/75/0/0 (size/max/drops/flus'
 b'hes); Total output drops: 0\r\n  Queueing strategy: fifo\r\n  Output queue: '
 b'0/40 (size/max)\r\n  5 minute input rate 1000 bits/sec, 2 packets/sec\r\n  5'
 b' minute output rate 1000 bits/sec, 1 packets/sec\r\n     6471372 packets i'
 b'nput, 422356173 bytes, 0 no buffer\r\n     Received 0 broadcasts (0 IP mul'
 b'ticasts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 input errors, 0 C'
 b'RC, 0 frame, 0 overrun, 0 ignored\r\n     250888 packets output, 27745935 '
 b'bytes, 0 underruns\r\n     0 output errors, 2 interface resets\r\n     0 unk'
 b'nown protocol drops\r\n     0 output buffer failures, 0 output buffers swa'
 b'pped out\r\nGigabitEthernet0/1 is down, line protocol is down (notconnect)'
 b' \r\n  Hardware is Gigabit Ethernet, address is 34a8.4e49.4701 (bia 34a8.4'
 b'e49.4701)\r\n  Description: Phone \r\n  MTU 1500 bytes, BW 1000000 Kbit/sec,'
 b' DLY 10 usec, \r\n     reliability 255/255, txload 1/255, rxload 1/255\r\n  '
 b'Encapsulation ARPA, loopback not set\r\n  Keepalive set (10 sec)\r\n  Auto-d'
 b'uplex, Auto-speed, media type is 10/100/1000BaseTX\r\n  input flow-control'
 b' is off, output flow-control is unsupported \r\n  ARP type: ARPA, ARP Time'
 b'out 04:00:00\r\n  Last input never, output 8w2d, output hang never\r\n  Last'
 b' clearing of "show interface" counters never\r\n  Input queue: 0/75/0/0 (s'
 b'ize/max/drops/flushes); Total output drops: 0\r\n  Queueing strategy: fifo'
 b'\r\n  Output queue: 0/40 (size/max)\r\n  5 minute input rate 0 bits/sec, 0 p'
 b'ackets/sec\r\n  5 minute output rate 0 bits/sec, 0 packets/sec\r\n     24968'
 b'650 packets input, 23692435714 bytes, 0 no buffer\r\n     Received 38531 b'
 b'roadcasts (31040 multicasts)\r\n     0 runts, 0 giants, 0 throttles \r\n    '
 b' 0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, '
 b'31040 multicast, 0 pause input\r\n     0 input packets with dribble condit'
 b'ion detected\r\n     40234657 packets output, 41158875157 bytes, 0 underru'
 b'ns\r\n     0 output errors, 0 collisions, 1 interface resets\r\n     0 unkno'
 b'wn protocol drops\r\n     0 babbles, 0 late collision, 0 deferred\r\n     0 '
 b'lost carrier, 0 no carrier, 0 pause output\r\n     0 output buffer failure'
 b's, 0 output buffers swapped out\r\nGigabitEthernet0/2 is up, line protocol'
 b' is up (connected) \r\n  Hardware is Gigabit Ethernet, address is 34a8.4e4'
 b'9.4702 (bia 34a8.4e49.4702)\r\n  Description: to Jump Box\r\n  MTU 1500 byte'
 b's, BW 1000000 Kbit/sec, DLY 10 usec, \r\n     reliability 255/255, txload '
 b'1/255, rxload 1/255\r\n  Encapsulation ARPA, loopback not set\r\n  Keepalive'
 b' set (10 sec)\r\n  Full-duplex, 1000Mb/s, media type is 10/100/1000BaseTX\r'
 b'\n  input flow-control is off, output flow-control is unsupported \r\n  ARP'
 b' type: ARPA, ARP Timeout 04:00:00\r\n  Last input never, output 00:00:01, '
 b'output hang never\r\n  Last clearing of "show interface" counters never\r\n '
 b' Input queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 246'
 b'7\r\n  Queueing strategy: fifo\r\n  Output queue: 0/40 (size/max)\r\n  5 m'
 b'inute input rate 2000 bits/sec, 2 packets/sec\r\n  5 minute output rate 30'
 b'00 bits/sec, 2 packets/sec\r\n     21379176 packets input, 16923403110 byt'
 b'es, 0 no buffer\r\n     Received 91471 broadcasts (9208 multicasts)\r\n     '
 b'0 runts, 0 giants, 0 throttles \r\n     0 input errors, 0 CRC, 0 frame, 0 '
 b'overrun, 0 ignored\r\n     0 watchdog, 9208 multicast, 4 pause input\r\n    '
 b' 0 input packets with dribble condition detected\r\n     28087287 packets '
 b'output, 6751205857 bytes, 0 underruns\r\n     0 output errors, 0 collision'
 b's, 2 interface resets\r\n     0 unknown protocol drops\r\n     0 babbles, 0 '
 b'late collision, 0 deferred\r\n     0 lost carrier, 0 no carrier, 0 pause o'
 b'utput\r\n     0 output buffer failures, 0 output buffers swapped out\r\nGiga'
 b'bitEthernet0/3 is administratively down, line protocol is down (disabled'
 b') \r\n  Hardware is Gigabit Ethernet, address is 34a8.4e49.4703 (bia 34a8.'
 b'4e49.4703)\r\n  MTU 1500 bytes, BW 10000 Kbit/sec, DLY 1000 usec, \r\n     r'
 b'eliability 255/255, txload 1/255, rxload 1/255\r\n  Encapsulation ARPA, lo'
 b'opback not set\r\n  Keepalive set (10 sec)\r\n  Auto-duplex, Auto-speed, med'
 b'ia type is 10/100/1000BaseTX\r\n  input flow-control is off, output flow-c'
 b'ontrol is unsupported \r\n  ARP type: ARPA, ARP Timeout 04:00:00\r\n  Last i'
 b'nput never, output never, output hang never\r\n  Last clearing of "show in'
 b'terface" counters never\r\n  Input queue: 0/75/0/0 (size/max/drops/flushes'
 b'); Total output drops: 0\r\n  Queueing strategy: fifo\r\n  Output queue: 0/4'
 b'0 (size/max)\r\n  5 minute input rate 0 bits/sec, 0 packets/sec\r\n  5 minut'
 b'e output rate 0 bits/sec, 0 packets/sec\r\n     0 packets input, 0 bytes, '
 b'0 no buffer\r\n     Received 0 broadcasts (0 multicasts)\r\n     0 runts, 0 '
 b'giants, 0 throttles \r\n     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 '
 b'ignored\r\n     0 watchdog, 0 multicast, 0 pause input\r\n     0 input packe'
 b'ts with dribble condition detected\r\n     0 packets output, 0 bytes, 0 un'
 b'derruns\r\n     0 output errors, 0 collisions, 0 interface resets\r\n     0 '
 b'unknown protocol drops\r\n     0 babbles, 0 late collision, 0 deferred\r\n  '
 b'   0 lost carrier, 0 no carrier, 0 pause output\r\n     0 output buffer fa'
 b'ilures, 0 output buffers swapped out\r\nGigabitEthernet0/4 is administrati'
 b'vely down, line protocol is down (disabled) \r\n  Hardware is Gigabit Ethe'
 b'rnet, address is 34a8.4e49.4704 (bia 34a8.4e49.4704)\r\n  MTU 1500 bytes, '
 b'BW 10000 Kbit/sec, DLY 1000 usec, \r\n     reliability 255/255, txload 1/2'
 b'55, rxload 1/255\r\n  Encapsulation ARPA, loopback not set\r\n  Keepalive se'
 b't (10 sec)\r\n  Auto-duplex, Auto-speed, media type is 10/100/1000BaseTX\r\n'
 b'  input flow-control is off, output flow-control is unsupported \r\n  ARP '
 b'type: ARPA, ARP Timeout 04:00:00\r\n  Last input never, output never, outp'
 b'ut hang never\r\n  Last clearing of "show interface" counters never\r\n  Inp'
 b'ut queue: 0/75/0/0 (size/max/drops/flushes); Total output drops: 0\r\n  Qu'
 b'eueing strategy: fifo\r\n  Output queue: 0/40 (size/max)\r\n  5 minute input'
 b' rate 0 bits/sec, 0 packets/sec\r\n  5 minute output rate 0 bits/sec, 0 pa'
 b'ckets/sec\r\n     0 packets input, 0 bytes, 0 no buffer\r\n     Received 0 b'
 b'roadcasts (0 multicasts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 i'
 b'nput errors, 0 CRC, 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, 0 mu'
 b'lticast, 0 pause input\r\n     0 input packets with dribble condition dete'
 b'cted\r\n     0 packets output, 0 bytes, 0 underruns\r\n     0 output errors,'
 b' 0 collisions, 0 interface resets\r\n     0 unknown protocol drops\r\n     0'
 b' babbles, 0 late collision, 0 deferred\r\n     0 lost carrier, 0 no carrie'
 b'r, 0 pause output\r\n     0 output buffer failures, 0 output buffers swapp'
 b'ed out\r\nGigabitEthernet0/5 is administratively down, line protocol is do'
 b'wn (disabled) \r\n  Hardware is Gigabit Ethernet, address is 34a8.4e49.470'
 b'5 (bia 34a8.4e49.4705)\r\n  MTU 1500 bytes, BW 10000 Kbit/sec, DLY 1000 us'
 b'ec, \r\n     reliability 255/255, txload 1/255, rxload 1/255\r\n  Encapsulat'
 b'ion ARPA, loopback not set\r\n  Keepalive set (10 sec)\r\n  Auto-duplex, Aut'
 b'o-speed, media type is 10/100/1000BaseTX\r\n  input flow-control is off, o'
 b'utput flow-control is unsupported \r\n  ARP type: ARPA, ARP Timeout 04:00:'
 b'00\r\n  Last input never, output never, output hang never\r\n  Last clearing'
 b' of "show interface" counters never\r\n  Input queue: 0/75/0/0 (size/max/d'
 b'rops/flushes); Total output drops: 0\r\n  Queueing strategy: fifo\r\n  Outpu'
 b't queue: 0/40 (size/max)\r\n  5 minute input rate 0 bits/sec, 0 packets/se'
 b'c\r\n  5 minute output rate 0 bits/sec, 0 packets/sec\r\n     0 packets inpu'
 b't, 0 bytes, 0 no buffer\r\n     Received 0 broadcasts (0 multicasts)\r\n    '
 b' 0 runts, 0 giants, 0 throttles \r\n     0 input errors, 0 CRC, 0 frame, 0'
 b' overrun, 0 ignored\r\n     0 watchdog, 0 multicast, 0 pause input\r\n     0'
 b' input packets with dribble condition detected\r\n     0 packets output, 0'
 b' bytes, 0 underruns\r\n     0 output errors, 0 collisions, 0 interface res'
 b'ets\r\n     0 unknown protocol drops\r\n     0 babbles, 0 late collision, 0 '
 b'deferred\r\n     0 lost carrier, 0 no carrier, 0 pause output\r\n     0 outp'
 b'ut buffer failures, 0 output buffers swapped out\r\nGigabitEthernet0/6 is '
 b'up, line protocol is up (connected) \r\n  Hardware is Gigabit Ethernet, ad'
 b'dress is 34a8.4e49.4706 (bia 34a8.4e49.4706)\r\n  Description: Cabin Switc'
 b'h\r\n  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec, \r\n     reliabilit'
 b'y 255/255, txload 1/255, rxload 1/255\r\n  Encapsulation ARPA, loopback no'
 b't set\r\n  Keepalive set (10 sec)\r\n  Full-duplex, 1000Mb/s, media type is '
 b'10/100/1000BaseTX\r\n  input flow-control is off, output flow-control is u'
 b'nsupported \r\n  ARP type: ARPA, ARP Timeout 04:00:00\r\n  Last input 00:00:'
 b'22, output 00:00:00, output hang never\r\n  Last clearing of "show interfa'
 b'ce" counters never\r\n  Input queue: 0/75/0/0 (size/max/drops/flushes); To'
 b'tal output drops: 0\r\n  Queueing strategy: fifo\r\n  Output queue: 0/40 (si'
 b'ze/max)\r\n  5 minute input rate 0 bits/sec, 0 packets/sec\r\n  5 minute out'
 b'put rate 10000 bits/sec, 11 packets/sec\r\n     986897 packets input, 1004'
 b'74435 bytes, 0 no buffer\r\n     Received 273275 broadcasts (273272 multic'
 b'asts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 input errors, 0 CRC,'
 b' 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, 273272 multicast, 0 pau'
 b'se input\r\n     0 input packets with dribble condition detected\r\n     890'
 b'29304 packets output, 14069151610 bytes, 0 underruns\r\n     0 output erro'
 b'rs, 0 collisions, 1 interface resets\r\n     0 unknown protocol drops\r\n   '
 b'  0 babbles, 0 late collision, 0 deferred\r\n     0 lost carrier, 0 no car'
 b'rier, 0 pause output\r\n     0 output buffer failures, 0 output buffers sw'
 b'apped out\r\nGigabitEthernet0/7 is down, line protocol is down (notconnect'
 b') \r\n  Hardware is Gigabit Ethernet, address is 34a8.4e49.4707 (bia 34a8.'
 b'4e49.4707)\r\n  Description: Desktop Corp Vlan\r\n  MTU 1500 bytes, BW 10000'
 b' Kbit/sec, DLY 1000 usec, \r\n     reliability 255/255, txload 1/255, rxlo'
 b'ad 1/255\r\n  Encapsulation ARPA, loopback not set\r\n  Keepalive set (10 se'
 b'c)\r\n  Auto-duplex, Auto-speed, media type is 10/100/1000BaseTX\r\n  input '
 b'flow-control is off, output flow-control is unsupported \r\n  ARP type: AR'
 b'PA, ARP Timeout 04:00:00\r\n  Last input never, output never, output hang '
 b'never\r\n  Last clearing of "show interface" counters never\r\n  Input queue'
 b': 0/75/0/0 (size/max/drops/flushes); Total output drops: 0\r\n  Queueing s'
 b'trategy: fifo\r\n  Output queue: 0/40 (size/max)\r\n  30 second input rate 0'
 b' bits/sec, 0 packets/sec\r\n  30 second output rate 0 bits/sec, 0 packets/'
 b'sec\r\n     0 packets input, 0 bytes, 0 no buffer\r\n     Received 0 broadca'
 b'sts (0 multicasts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 input e'
 b'rrors, 0 CRC, 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, 0 multicas'
 b't, 0 pause input\r\n     0 input packets with dribble condition detected\r\n'
 b'     0 packets output, 0 bytes, 0 underruns\r\n     0 output errors, 0 col'
 b'lisions, 1 interface resets\r\n     0 unknown protocol drops\r\n     0 babbl'
 b'es, 0 late collision, 0 deferred\r\n     0 lost carrier, 0 no carrier, 0 p'
 b'ause output\r\n     0 output buffer failures, 0 output buffers swapped out'
 b'\r\nGigabitEthernet0/8 is up, line protocol is up (connected) \r\n  Hardware'
 b' is Gigabit Ethernet, address is 34a8.4e49.4708 (bia 34a8.4e49.4708)\r\n  '
 b'Description: Desktop DSL\r\n  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 '
 b'usec, \r\n     reliability 255/255, txload 1/255, rxload 1/255\r\n  Encapsul'
 b'ation ARPA, loopback not set\r\n  Keepalive set (10 sec)\r\n  Full-duplex, 1'
 b'000Mb/s, media type is 10/100/1000BaseTX\r\n  input flow-control is off, o'
 b'utput flow-control is unsupported \r\n  ARP type: ARPA, ARP Timeout 04:00:'
 b'00\r\n  Last input never, output 00:00:01, output hang never\r\n  Last clear'
 b'ing of "show interface" counters never\r\n  Input queue: 0/75/0/0 (size/ma'
 b'x/drops/flushes); Total output drops: 0\r\n  Queueing strategy: fifo\r\n  Ou'
 b'tput queue: 0/40 (size/max)\r\n  30 second input rate 0 bits/sec, 0 packet'
 b's/sec\r\n  30 second output rate 2000 bits/sec, 2 packets/sec\r\n     601847'
 b' packets input, 46035270 bytes, 0 no buffer\r\n     Received 66 broadcasts'
 b' (0 multicasts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 input erro'
 b'rs, 0 CRC, 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, 0 multicast, '
 b'0 pause input\r\n     0 input packets with dribble condition detected\r\n   '
 b'  12384240 packets output, 1528016366 bytes, 0 underruns\r\n     0 output '
 b'errors, 0 collisions, 1 interface resets\r\n     0 unknown protocol drops\r'
 b'\n     0 babbles, 0 late collision, 0 deferred\r\n     0 lost carrier, 0 no'
 b' carrier, 0 pause output\r\n     0 output buffer failures, 0 output buffer'
 b's swapped out\r\nGigabitEthernet0/9 is administratively down, line protoco'
 b'l is down (disabled) \r\n  Hardware is Gigabit Ethernet, address is 34a8.4'
 b'e49.4709 (bia 34a8.4e49.4709)\r\n  MTU 1500 bytes, BW 10000 Kbit/sec, DLY '
 b'1000 usec, \r\n     reliability 255/255, txload 1/255, rxload 1/255\r\n  Enc'
 b'apsulation ARPA, loopback not set\r\n  Keepalive not set\r\n  Auto-duplex, A'
 b'uto-speed, link type is auto, media type is 1000BaseSX SFP\r\n  input flow'
 b'-control is off, output flow-control is unsupported \r\n  ARP type: ARPA, '
 b'ARP Timeout 04:00:00\r\n  Last input never, output never, output hang neve'
 b'r\r\n  Last clearing of "show interface" counters never\r\n  Input queue: 0/'
 b'75/0/0 (size/max/drops/flushes); Total output drops: 0\r\n  Queueing strat'
 b'egy: fifo\r\n  Output queue: 0/40 (size/max)\r\n  5 minute input rate 0 bits'
 b'/sec, 0 packets/sec\r\n  5 minute output rate 0 bits/sec, 0 packets/sec\r\n '
 b'    0 packets input, 0 bytes, 0 no buffer\r\n     Received 0 broadcasts (0'
 b' multicasts)\r\n     0 runts, 0 giants, 0 throttles \r\n     0 input errors,'
 b' 0 CRC, 0 frame, 0 overrun, 0 ignored\r\n     0 watchdog, 0 multicast, 0 p'
 b'ause input\r\n     0 input packets with dribble condition detected\r\n     0'
 b' packets output, 0 bytes, 0 underruns\r\n     0 output errors, 0 collision'
 b's, 0 interface resets\r\n     0 unknown protocol drops\r\n     0 babbles, 0 '
 b'late collision, 0 deferred\r\n     0 lost carrier, 0 no carrier, 0 pause o'
 b'utput\r\n     0 output buffer failures, 0 output buffers swapped out\r\nGiga'
 b'bitEthernet0/10 is up, line protocol is up (connected) \r\n  Hardware is G'
 b'igabit Ethernet, address is 34a8.4e49.470a (bia 34a8.4e49.470a)\r\n  Descr'
 b'iption: NCLDSL-Trunk\r\n  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec'
 b', \r\n     reliability 255/255, txload 1/255, rxload 1/255\r\n  Encapsulatio'
 b'n ARPA, loopback not set\r\n  Keepalive not set\r\n  Full-duplex, 1000Mb/s, '
 b'link type is auto, media type is 10/100/1000BaseTX\r\n  input flow-control'
 b' is off, output flow-control is unsupported \r\n  ARP type: ARPA, ARP Time'
 b'out 04:00:00\r\n  Last input 00:00:00, output 00:00:00, output hang never\r'
 b'\n  Last clearing of "show interface" counters never\r\n  Input queue: 0/75'
 b'/0/0 (size/max/drops/flushes); Total output drops: 0\r\n  Queueing strateg'
 b'y: fifo\r\n  Output queue: 0/40 (size/max)\r\n  30 second input rate 40000 b'
 b'its/sec, 48 packets/sec\r\n  30 second output rate 6000 bits/sec, 2 packet'
 b's/sec\r\n     548205006 packets input, 118827369022 bytes, 0 no buffer\r\n  '
 b'   Received 449611062 broadcasts (278741158 multicasts)\r\n     0 runts, 0'
 b' giants, 0 throttles \r\n     5 input errors, 4 CRC, 0 frame, 0 overrun, 0'
 b' ignored\r\n     0 watchdog, 278741158 multicast, 0 pause input\r\n     0 in'
 b'put packets with dribble condition detected\r\n     50598343 packets outpu'
 b't, 41171243431 bytes, 0 underruns\r\n     0 output errors, 0 collisions, 1'
 b' interface resets\r\n     0 unknown protocol drops\r\n     0 babbles, 0 late'
 b' collision, 0 deferred\r\n     0 lost carrier, 0 no carrier, 0 pause outpu'
 b't\r\n     0 output buffer failures, 0 output buffers swapped out\r\nAleandro'
 b'-Desk#')


